import '@bedrock-apis/va-test/suites';

import { runAndCompare, VirtualApiEnvironment } from '@bedrock-apis/va-test';
import { Context, ContextUtils } from '@bedrock-apis/virtual-apis';
import { world } from '@minecraft/server';
import fs from 'node:fs/promises';
import { testsResultProvider } from '../dump/provider';

world.afterEvents.worldLoad.subscribe(async () => {
   const bdsReports = (await testsResultProvider.read()).tests;
   const result = await runAndCompare(bdsReports, new VirtualApiEnvironment());

   console.log('\n\n');
   console.log(result);
   console.log('\n\n');

   const header = `### API Report
   
   This is an autogenerated report. It shows how much tests are not passing from the [bds dump tests](./libs/va-test/src/suites) test suite with all enabled [VirtualApi core plugins](./packages/core-plugin/).

Later this can be used with bapi scan to autogenerate list of apis you may want to implement to fully utilize VirtualApi in your project

### Report

\`\`\`

`;

   await fs.writeFile(process.env.REPORT_PATH ?? process.argv[3] ?? 'INCOMPATIBILITY.md', header + result + `\n\`\`\``);

   const context = Context.getContext(0);
   const stats = ContextUtils.getStats(context!, context!.getModuleSymbol('@minecraft/server-bindings')!);
   console.log('Implemented symbols: ', stats.text);
});
