import '@bedrock-apis/core-plugin';

import { readTestReport } from '@bedrock-apis/bds-dumps/api';
import { loadModules } from '@bedrock-apis/va-loader/node';
import { Context } from '@bedrock-apis/virtual-apis';
import fs from 'node:fs/promises';

const context = new Context();
context.configureAndLoadPlugins({});
await loadModules(context);

main();

async function main() {
   await import('./suites/all');

   const { world } = await import('@minecraft/server');
   const { runAndCompare } = await import('./compare');
   const { VirtualApiEnvironment } = await import('./environment/va');

   world.afterEvents.worldLoad.subscribe(async () => {
      const bdsReports = await readTestReport();
      const result = await runAndCompare(bdsReports, new VirtualApiEnvironment());

      console.log('\n\n');
      console.log(result);
      console.log('\n\n');

      const header = `### API Report
   
   This is an autogenerated report. It shows how much tests are not passing from the [bds dump tests](./libs/va-test/src/suites) test suite with all enabled [VirtualApi core plugins](./packages/core-plugin/).

Later this can be used with bapi scan to autogenerate list of apis you may want to implement to fully utilize VirtualApi in your project

### Report

\`\`\`

`;

      await fs.writeFile('INCOMPATIBILITY.md', header + result + `\n\`\`\``);

      const stats = Context.getContext(0)!.getStats('@minecraft/server');
      console.log('Implemented symbols: ', stats.text);
   });
}
