// Plugin and loader are imported by command line
import './suites/all';

import { readTestReport } from '@bedrock-apis/bds-dumps/api';
import { world } from '@minecraft/server';
import fs from 'node:fs/promises';
import { runAndCompare } from './compare';
import { VirtualApiEnvironment } from './environment/va';

world.afterEvents.worldLoad.subscribe(async () => {
   const bdsReports = await readTestReport();
   const result = await runAndCompare(bdsReports, new VirtualApiEnvironment());

   console.log('\n\n');
   console.log(result);
   console.log('\n\n');

   const header = `### API Report

This is an autogenerated report. It shows how much tests are not passing from the [bds dump tests](./libs/va-test/src/suites) test suite with all enabled [VirtualApi core plugins](./packages/core-plugin/).

Later this can be used with bapi scan to autogenerate list of apis you may want to implement to fully utilize VirtualApi in your project

### Report

\`\`\`

`;

   await fs.writeFile('INCOMPATIBILITY.md', header + result + `\n\`\`\``);

   // Stats
   // const ctx = Context.getContext(0)!;
   // const mod = ctx!.modules.get('@minecraft/server')!;
   // console.log(
   //    mod.invocables.size,
   //    ctx.implementations.get(mod.nameVersion)!.size,
   //    [...ctx.implementations.get(mod.nameVersion)!.keys()].join('\n'),
   // );
});
