import fs from 'node:fs/promises';
import results from '../../../bds-docs-stable/reports/api.json' with { type: 'json' };
import { runAndCompare } from './compare';
import { VirtualApiEnvironment } from './enviroment/va';

const result = await runAndCompare(results, new VirtualApiEnvironment());

console.log('\n\n');
console.log(result);
console.log('\n\n');

const header = `### API Report

This is an autogenerated report. It shows how much tests are not passing from the [bds-docs](./bds-docs/test-runner/suites) test suite with all enabled [VirtualApi core plugins](./src/plugin/core/).

Later this can be used with bapi scan to autogenerate list of apis you may want to implement to fully utilize VirtualApi in your project

### Report

\`\`\`

`;

await fs.writeFile('INCOMPATABILITY.md', header + result + `\n\`\`\``);
