import fs from 'node:fs/promises';
import module from 'node:module';
import path from 'node:path';
import { FS } from './src/tooling/typesafe-fs/directories';

await fs.rm(FS.dist.DIR, { force: true, recursive: true });

const PACKAGE_JSON: typeof import('./package.json') = JSON.parse(await fs.readFile(FS.package_json, 'utf-8'));
const DEPENDENCIES = Object.keys(PACKAGE_JSON.devDependencies).concat(Object.keys(PACKAGE_JSON.dependencies));
const EXTERNAL = [...module.builtinModules, /node/, ...DEPENDENCIES];
const PLUGINS = Object.entries(FS.src.core_plugins)
   .filter(e => e[0] !== 'DIR')
   .map(([filename, path]) => ({
      filename: filename.replace(/_ts$/, '.js').replaceAll('_', '-'),
      path,
   }));

export default [
   {
      input: FS.src.package_builder.index_ts,
      output: { file: FS.dist.package_builder_js, sourcemap: true },
      external: EXTERNAL,
   },
   {
      input: [
         FS.src.api_builder.index_ts,
         FS.src.loader.node.hooks_ts,
         FS.src.loader.node.loader_ts,
         FS.src.loader.vitest_ts,
         ...PLUGINS.map(e => e.path),
      ],
      output: { dir: FS.dist.DIR, sourcemap: true },
      external: EXTERNAL,
   },
   {
      input: FS.src.tooling.eslint.plugin_ts,
      output: { file: FS.dist.eslint_plugin_js, sourcemap: true },
      external: EXTERNAL,
   },
] satisfies import('rolldown').ConfigExport;

// Write package exports
await fs.mkdir(FS.dist.plugins.DIR, { recursive: true });
await Promise.all(
   PLUGINS.map(({ filename }) => {
      return fs.writeFile(path.join(FS.dist.plugins.DIR, filename), `export * from '../${filename}'`);
   }),
);

await fs.writeFile(
   FS.dist.plugins.all_js,
   `// This file is autogenerated by ${import.meta.filename}
import './modules.js';

${PLUGINS.filter(e => e.filename !== 'modules.js')
      .map(({ filename }) => `import './${filename}';`)
      .join('\r\n')}
`);

PACKAGE_JSON.exports = Object.fromEntries([
   ['.', { default: FS.dist.index_js, types: FS.dist.src.api_builder.index_d_ts }],
   ['./package.json', FS.package_json],
   ['./modules/*', FS.modules.DIR + '*'],
   ['./plugins/*', { default: FS.dist.plugins.DIR + '*.js', types: FS.dist.src.core_plugins.DIR + '*.d.ts' }],
   ['./loader', FS.dist.loader_js],
   ['./eslint-plugin', { default: FS.dist.eslint_plugin_js, types: FS.dist.src.tooling.eslint.plugin_d_ts }],
   ['./vitest', { default: FS.dist.vitest_js, types: FS.dist.src.loader.vitest_d_ts }],
]);

await fs.writeFile(FS.package_json, JSON.stringify(PACKAGE_JSON, null, 3).replaceAll('\n', '\r\n'));
